name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Add server to known hosts
        run: ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # Step 3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      # Step 4
      - name: Build Binary
        run: |
          go mod tidy
          go build -o app .

      # Step 5
      - name: Deploy to Server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          scp -P $DEPLOY_PORT ./app $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/app.tmp
          ssh -p 4422 ussa@95.85.108.122 'mv @$DEPLOY_HOST/app.tmp @$DEPLOY_HOST/app'
          ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "echo '$SUDO_PASSWORD' | sudo -S systemctl restart muck.service"